agents:
  llm:
    api_key: ${API_KEY}
    model: gpt-4o
    provider: openai
api_key: ${API_KEY}
llm:
  api_key: ${API_KEY}
  model: gpt-4o
  provider: openai
max_tokens: 2000
model: gpt-4o
provider: openai
temperature: 0.7
top_p: 1.0
